### Create a new Report
POST http://localhost:3000/reports
Content-Type: application/json

{
    "make": "toyota",
    "model": "latest",
    "year": 2020,
    "mileage": 1000,
    "lng": 23.45566,
    "lat": 3.45566,
    "price": 499000
}
### Approve an existing report 
PATCH  http://localhost:3000/reports/9
Content-Type: application/json

{
    "approved": true
    
}